### PR TITLE
Removing redundancy in test ObservedValueTest

### PR DESCRIPTION
**Pull request by mtupce**
Removed redundancy in test ObservedValueTest (st58266)

### CODE REVIEW

**Comment by rodi0878** [comment]
tests are broken by this change, please fix

**Comment by mtupce** [comment]
No changes, except merge of latest changes.
Checked on my pc (after merging latest changes), no errors are showing on my pc. From github test it seems that @ BeforeEach doesn't triggered in github. Is there different behaviour in github test?

**Comment by rodi0878** [comment]
still not working, workflow in github is running standard "mvn test" command for test running

**Comment by mtupce** [comment]
Added Maven-surefire_plugin to pom.xml
It seems maven doesn't normally run Junit tests correctly, unless plugin is added. My Maven test went without error.

**Pull request merged**
